# Generated by Django 6.0.7 on 2026-07-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
