# Generated by Django 6.0.7 on 2026-07-31 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos_app", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="videos_app.categoria"
            ),
        ),
    ]
