# Generated by Django 6.0.7 on 2026-07-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos_app", "0003_alter_video_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="vistas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
