# Generated by Django 6.0.7 on 2026-07-31 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos_app", "0004_video_vistas"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fecha_subida",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
