# Generated by Django 6.0.7 on 2026-07-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos_app", "0005_video_fecha_subida"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-fecha_subida"]},
        ),
    ]
